#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server using scp(Secure copy protocol)

if [ $# -gt 3 ]; then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
