#!/usr/bin/env bash
# A script to install nginx on a server and set it up to display 'Hello World'
# at its root when queried with a GET request.

# Update package lists and install nginx
sudo apt update
sudo apt install nginx -y

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Change the content of the default page
echo 'Hello World!                 ' | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Restart Nginx using service command (not systemctl)
sudo service nginx restart
