#!/usr/bin/env bash
# A script to Configure your Nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.

# Update package lists and install nginx
sudo apt update
sudo apt install nginx -y

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Change the content of the default page
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Setup custopm 404 error page
sudo mkdir -p /var/www/html/error_pages # Create directory if not exists
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_pages/404.html >/dev/null

# Make /redirect_me is redirect to another page(and clean default host configuration).
echo "\
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html{
        root /var/www/html/error_pages/;
        internal;
    }
}" | sudo tee /etc/nginx/sites-available/default >/dev/null

# Restart Nginx using service command (not systemctl)
sudo service nginx restart
