#!/usr/bin/env bash
#Displays Best School 10 times (using while), but also 'hi' on 9th round

i=1
while (( i <= 10 )); do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
