#!/usr/bin/env bash
#configures an Ubuntu server with the below requirements(considering docker):
#	localhost resolves to 127.0.0.2
#	facebook.com resolves to 8.8.8.8


# Make a copy of /etc/hosts
cp /etc/hosts ~/hosts.new

# Update localhost resolution to 127.0.0.2
echo "127.0.0.2 localhost" >> ~/hosts.new

# Update facebook.com resolution to 8.8.8.8
echo "8.8.8.8 facebook.com" >> ~/hosts.new

# Overwrite the original /etc/hosts file with the modified one
cp -f ~/hosts.new /etc/hosts
